### PR TITLE
Variables in for/while-loops and switch

### LINKED ISSUE #205: for loop: support variables
Currently, the `for` loop doesn't support variable declarations in the scope of the loop. It should support them.

Look for the number `205` in the code to find clues to implement this feature.

### PR DESCRIPTION
**Pull request by DavTen**
Closes #205

### CODE REVIEW

**Comment by kant2002** [comment]
If you probably notice this look like special cases of other features like nested block definitions. Can you also uncomment https://github.com/ForNeVeR/Cesium/blob/main/Cesium.IntegrationTests/declaration_scopes.ignore.c and check that this and more generic case of couple nested blocks would work. If we decouple declaration scopes from statements we would be able to have all such cases covered

**Comment by DavTen** [comment]
Okay, accepted. I'll pay attention to more generic case. It seems that variables are better handle around CompoundStatement, that would include all other cases. What are you think? @kant2002

**Comment by kant2002** [comment]
@DavTen I think `CompoundStatement` should be fine. You may take into account that switch by itself does not create scope IIRC. So you may need introduce special scopeless CompoundStatement either as separate class, or via additional property

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Comment by ForNeVeR** [comment]
You may proceed with related refactorings of `CompoundStatement` in a new PR if you wish, but this is already good enough to be merged.

**Pull request merged**
