### PR TITLE
Declare variables by IType, and not by VariableDef

### PR DESCRIPTION
**Pull request by kant2002**
That way we working more on C-types then Cecil internals

### CODE REVIEW

**Review by ForNeVeR — COMMENTED** [review]
This is all nice, but we'll have to redesign several tests (the ones that were just defining local variables), since they have now stopped doing what they were supposed to.

**Comment by kant2002** [comment]
What tests in your opinion require redesign?

**Comment by kant2002** [comment]
Or more specifically, should I try preserve existing behavior?

**Comment by ForNeVeR** [comment]
- `Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FunctionPtrTest.verified.txt`
- `Cesium.CodeGen.Tests/verified/CodeGenMethodTests.FunctionPtrWithParamsTest.verified.txt`
- `Cesium.CodeGen.Tests/verified/CodeGenMethodTests.ImplicitReturnAllowedForMain.verified.txt`
- `Cesium.CodeGen.Tests/verified/CodeGenMethodTests.PrimitiveTypes.verified.txt`
- `Cesium.CodeGen.Tests/verified/CodeGenTypeTests.BasicTypeDef.verified.txt`
- `Cesium.CodeGen.Tests/verified/CodeGenTypeTests.TypeDefStructUsage.verified.txt`

I think it would be enough to move the declarations to global level in these tests to force-emit the fields for them.No need to preserve the old behavior.

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Comment by kant2002** [comment]
What do you think if I add variable initializers to the variables. THat way corresponding variables would be used, and that's trigger local variables back.
Regarding moving type declarations on the global level. Because that trigger different path, I would consider this as separate set of test cases, which I gladly add if you think that's worth it.

**Comment by ForNeVeR** [comment]
You did good.

**Pull request merged**
