### PR TITLE
Update TokenExtensions.cs

### PR DESCRIPTION
**Pull request by Evgeny608799**
Modification of `current >= '0' && current <= '9'` to `Char.IsDigit()`

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Sadly, I don't believe this change is correct, I am sorry :(

`Char.IsDigit` is documented to accept Unicode digits as well (for example, `६` is a digit as well!), while the C standard only mandates support for the standard digits `0…9`.

I would propose to update it and extract the same check for `0…9` to a common method.

**Review by ForNeVeR — CHANGES_REQUESTED** [review]
Sadly, I don't believe this change is correct, I am sorry :(

`Char.IsDigit` is documented to accept Unicode digits as well (for example, `६` is a digit as well!), while the C standard only mandates support for the standard digits `0…9`.

I would propose to update it and extract the same check for `0…9` to a common method.

**Comment by Evgeny608799** [comment]
Replaced `Char.IsDigit` with `Char.IsAsciiDigit` to check digits only in **ASCII**

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
