### PR TITLE
Add _Bool type

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
[We have it documented](https://github.com/ForNeVeR/Cesium/blob/main/docs/type-system.md) to correspond to `System.Bool`, though. Are you sure we want to change that decision?

**Comment by ForNeVeR** [comment]
Tests say
```
Right operand of type PrimitiveType { Kind = Bool } is not numeric.
```

Heh. Need help with that?

**Comment by kant2002** [comment]
> Heh. Need help with that?

Compasion with my humane limitations would be enough!

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
