### PR TITLE
Fix SetValueExpression emitting

### LINKED ISSUE #409: Fix integration test `switch/no_side_effects.ignore.c`
Right now, it's ignored due to "bad SetValueExpression results in unbalanced stack".

### LINKED ISSUE #411: Handle assign-as-expressions correctly
See `TODO[#411]`, `duff_device.c`:
```c
    // assignments are broken as expressions currently
    // switch(c&3) while((c-=4)>=0) {
    switch(c&3) while(c >= 4) {
      […]
```

### PR DESCRIPTION
**Pull request by zawodskoj**
SetValueExpression has invalid type - type is always equal to type of value to set, but actual emitted code always leave empty stack, so SetValueExpression cannot be used as value and when it is used compiler produces invalid IL.

This PR fixes that - compound assignments now work correctly
This allows `while (i += 1)` and `while (i++)` to be compiled correctly

Fun fact - this code will result in 1 in `i`

```
var i = 0;
i += i += 1;
```

(there's no sequence points, so who cares, but this it worth noting)

- Closes #409.
- Closes #411.

### CODE REVIEW

**Comment by zawodskoj** [comment]
Sequence-point trickery does not play nicely with GCC (`i = i++` does not actually increment anything)

**Comment by ForNeVeR** [comment]
Please rebase on `main` to proceed with this :)

**Comment by zawodskoj** [comment]
Rebased on main

**Comment by zawodskoj** [comment]
switch/no_side_effects is working now - uncommented

**Comment by ForNeVeR** [comment]
Whoa, this also fixes #411!

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
