### PR TITLE
7645re/added conditional elif block

### LINKED ISSUE #517: Preprocessor: support `#elif`
Example:
```c
#if FOO
// foo
#elif BAR
// bar
#endif
```

Currently, we don't support `#elif`.

### PR DESCRIPTION
**Pull request by 7645re**
Closes #517.

this is still a draft, there are problems with naming, but I'm still more concerned about finding more corner cases to fully test the code for performance and optimization

### CODE REVIEW

**Review by ForNeVeR — APPROVED** [review]
So far looks good to me. Please let me know when you are finished with the naming stuff you mentioned.

**Comment by kant2002** [comment]
Not important, but maybe `#elifdef` and `#elifndef` can be added here as well?

**Comment by ForNeVeR** [comment]
I would suggest against extending the task definition. Let's focus on immediate issues and add other features later.

In particular, #61 is blocked on `#elif` specifically.

**Comment by 7645re** [comment]
Okay, let's finish this task and then create an issue marked area:standard-support?

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
