### PR TITLE
Add support for named structs

### LINKED ISSUE #218: Support named structures
As of now, this isn't supported:
```c
struct foo {
  int x;
};

struct foo xx;
```

It should be.

Look for the number `218` in the code to find clues to implement this feature.

### PR DESCRIPTION
**Pull request by kant2002**
Closes #218

### CODE REVIEW

**Review by ForNeVeR — CHANGES_REQUESTED** [review]
The example from #218 doesn't seem to work; this yields a parse exception.
```
struct Foo
{
    int x;
};

int main(void) {
    struct Foo foo;
    return 0;
}
```

**Comment by ForNeVeR** [comment]
Also I should note that your solution doesn't seem to follow the C standard. I would accept such a solution, though (and would open a new issue to improve it in the future). But let's make the local declaration parser standard-compliant at least :)

What's up with it being not standard-compliant?

The standard essentially introduces two "namespaces" for types: one namespace for `typedef`s, and a second one for named type declarations such as `struct Foo` or `union Uoo`.

`typedef`s may be referred by their given name, while named types should be only referred by their category (`struct` or `union`) and a name, such as `struct Foo`.

Also, it's possible to have totally different things named `Foo` and `struct Foo` in your program:
```c
struct Foo { int A; };
typedef struct { int B; } Foo;
int main(void) {
  struct Foo a;
  Foo b;
  a.A = 0;
  b.B = 0;
}
```

Ineterestingly, it's _disallowed_ to declare both `union Foo` and `struct Foo` at the same translation unit. Only `typedef … Foo` and `struct` (or `union`) `Foo`.

I think we can for now ignore this kind of name collisions (and open a future improvement issue for that), but we should _at least_ parse valid C programs that refer to named types as `struct X`.

**Comment by ForNeVeR** [comment]
Is Windows test failure caused by #350?

**Comment by kant2002** [comment]
No. I did fix error mentioned in #350 in #362 but issue is not related to verification failures

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
