### PR TITLE
Add Test Adapter for Cesium Integration tests

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Review by ForNeVeR — CHANGES_REQUESTED** [review]
1. Please include the new projects into the solution file.
2. It looks like the tests aren't runnable, yet? Will you fix that?

**Comment by ForNeVeR** [comment]
Now CI seems broken, will you take a look?

**Comment by kant2002** [comment]
I see following issues with current implementation;
- Locally I have flaky comparison of output from Cesium and VC compiled applications
- CI behave strangely on Ubuntu.

**Comment by ForNeVeR** [comment]
Ok, I'll try to investigate what happens here on the weekend.

**Pull request closed without merging**
